LOG_FILE : logs/gateway.log
PRI_KEY_FILE : pri.pem
PUB_KEY_FILE : pub.pem
PORT : 9090
#http server
READ_TIMEOUT : 300
WRITE_TIMEOUT : 300
SHUTDOWN_TIMEOUT : 600
JWT_TIMEOUT : 86400
#http client
CLIENT_TIMEOUT : 300